### ISSUE TITLE
Location enum doesn't map from city name to enum's constant

### ISSUE THREAD

**Issue by mihhail-m** [loadero/loadero-java#24]
Hi.

Unfortunately, something that was missed during testing. Currently it is only possible to map AWS instances strings to Locations enum constants. Hence it is not possible to create, for example, **Location.OREGON** from string "oregon". Perhaps, for user experience, it would be nice to create some solution for that issue. 

Example:
```java
assertEquals(Location.OREGON.toString(), "oregon") // fails
assertEquals(Location.OREGON.toString(), "us-west-2") // passes
```

**Comment by ajpetersons** [comment]
If we can have both versions, then it might be fine having functionality like this. The locations are mapped to AWS regions and Loadero API expects the AWS region format. 

Having the human-readable enum name as `OREGON`, but the underlying value as `us-west-2` is OK in a programmatic environment, i would say.

**Comment by mihhail-m** [comment]
Yeah, it's actually okay-ish as it is right now. I just stumbled upon the use case, where I have .json file with participant's configuration that is later used for creating participant in Loadero. And when serializing this .json file into respective class I needed to specify `us-west-2` location instead of just `oregon`. This is fine and all, but finding information which AWS region maps to which location is not that straightforward, hence this is more of a suggestion to make something like this possible. Although, I am not currently sure how.

**Comment by ajpetersons** [comment]
I see what you mean. Maybe we should do some code annotations or something. `.toString()` should always produce `us-west-2`, parsing from string could work both ways

**Comment by mihhail-m** [comment]
Okay, so, I actually misunderstood what was my issue here 😬 It actually wasn't possible to deserialize **Location** enum value, from "oregon", because in the annotation **@SerializedName**  it was only specified AWS instance's name, hence something like this wasn't possible: 

```java
        String configJson1 = "frankfurt";
        Location frankfurt = gson.fromJson(configJson1, Location.class);
        Assertions.assertEquals(Location.FRANKFURT, frankfurt);
```

But if we add to **@SerializedName(value = "eu-central-1", alternate = "frankfurt")** then the above code would be legit and probably will simplify serialization on user's side when he/she will be using **Location** enum for whatever reasons.
The question is, whether is it necessary or not? The change itself won't be big only needed to add **alternate** with respective city name next to AWS instance's name.

**Comment by ajpetersons** [comment]
I think we could do the alternate names, especially since we have taken a side step with ENUM naming.
